### ISSUE TITLE
fakelag is fucked up

### ISSUE THREAD

**Issue by rrhyast** [notgoodusename/OsirisAndExtra#291]
doesn't work either.

**Comment by notgoodusename** [comment]
>using over 14 fake lag gives a bit of delay on the shots

Valve servers only allow up to 8 ticks of chokedpackets while most community servers allow 16 chokedpackets, obviously chokedpackets is [clamped](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/Fakelag.cpp#L38) in Fakelag.cpp, so what you said is irrelevant since anything beyond 8 ticks is the same
