### ISSUE TITLE
pattern injecting error

### ISSUE THREAD

**Issue by Fearqueesha** [notgoodusename/OsirisAndExtra#374]
when i inject the dll, i get an error saying "Failed to find pattern #5" and 6, 63, 91 etc. only started happening after csgo update.

**Comment by LaptisMinecraft** [comment]
for me it's 8 63 65 and then csgo crashes
@notgoodusename pls fix for the csgo update

**Comment by methylbenzene** [comment]
@notgoodusename pls fix

**Comment by LaptisMinecraft** [comment]
As far as I know, pattern 63 (Memory.cpp, L164)
`sendDatagram = findPattern(ENGINE_DLL, "\x55\x8B\xEC\x83\xE4\xF0\xB8????\xE8????\x56\x57\x8B\xF9\x89\x7C\x24\x18");`
and pattern 65 (Memory.cpp, L168)
`lookUpBone = relativeToAbsolute<decltype(lookUpBone)>(findPattern(CLIENT_DLL, "\xE8????\x85\xC0\x78\x4E") + 1);`
need to be updated.
Additionally, the relativeToAbsolute() causes access violation because findPattern() returns nullptr.

**Comment by LaptisMinecraft** [comment]
![屏幕截图 2022-10-22 202903](https://user-images.githubusercontent.com/50985752/197339081-64d4608d-a885-49aa-a285-4593eb58f9bf.png)

**Comment by LaptisMinecraft** [comment]
fix asap pls @notgoodusename

**Comment by notgoodusename** [comment]
stop tagging me

**Comment by Navoichyk** [comment]
im getting pattern 98 as well

**Comment by Utkukck11** [comment]
just calm down touch some grass and wait for the update

**Comment by LaptisMinecraft** [comment]
It seems that pattern 98 is unused. So, I just commented it in Memory.cpp and Hooks.cpp, and it works, it injects fine.

**Comment by Navoichyk** [comment]
> It seems that pattern 98 is unused. So, I just commented it in Memory.cpp and Hooks.cpp, and it works, it injects fine.

true. which one is pattern 98 in hooks and memory
